name: ckb

on:
  push:
    branches:
    - '**'
  workflow_dispatch:
    branches:
    - '**'
  pull_request:
    branches:
    - master
    - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        wget 'https://github.com/nervosnetwork/ckb-standalone-debugger/releases/download/v0.107.0/ckb-debugger-linux-x64.tar.gz'
        tar zxvf ckb-debugger-linux-x64.tar.gz
        chmod +x ckb-debugger
        cp ckb-debugger ~/.cargo/bin
        ckb-debugger --version

    - name: Build test files
      run: |
        docker run --rm -v "$PWD:/code:Z" --workdir /code --entrypoint /bin/bash nervos/ckb-riscv-gnu-toolchain:gnu-focal-20230214 -c 'VERBOSE=1 CC=riscv64-unknown-linux-gnu-gcc make clean ckb_execs'

    - name: Run tests
      run: |
        ckb-debugger --max-cycles 999999999999 --bin "${{ github.workspace }}/build/ec_self_tests" vectors |& fgrep 'Run result: 0'
